app = 'daneel-discord-bot'
primary_region = 'ord'

[build]
  args = { NODE_ENV = "production" }

[env]
  NODE_ENV = "production"

# Process configuration
[processes]
  app = "sh -c 'cd /app/packages/discord-bot && node dist/index.js'"

# VM configuration
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1