app = 'daneel-discord-bot'
primary_region = 'ord'

[build]
  args = { NODE_ENV = "production" }

[env]
  NODE_ENV = "production"

# Process configuration
[processes]
  app = "/app/start.sh"
  web = "/app/start.sh"

# HTTP service configuration
[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# VM configuration
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1