packages:
    - packages/*
syncInjectedDepsAfterScripts:
    - build
injectWorkspacePackages: true
catalog:
    "@discordjs/voice": ^0.19.0
    "@eslint/js": ^9.39.2
    "@marsidev/react-turnstile": ^1.4.1
    "@openai/agents": ^0.3.7
    "@sapphire/shapeshift": ^4.0.0
    "@swc/core": ^1.15.8
    "@swc/helpers": ^0.5.18
    "@types/better-sqlite3": ^7.6.13
    "@types/body-parser": ^1.19.6
    "@types/express": ^5.0.6
    "@types/js-yaml": ^4.0.9
    "@types/mime-types": ^3.0.1
    "@types/node": ^24.10.4
    "@types/react": 18.3.27
    "@types/react-dom": 18.3.7
    "@types/ws": ^8.18.1
    "@typescript-eslint/eslint-plugin": ^8.51.0
    "@typescript-eslint/parser": ^8.51.0
    "@vitejs/plugin-react": ^5.1.2
    autoprefixer: ^10.4.23
    better-sqlite3: ^11.10.0
    body-parser: ^2.2.1
    cloudinary: ^2.8.0
    concurrently: ^8.2.2
    copyfiles: ^2.4.1
    cross-env: ^10.1.0
    csstype: 3.2.3
    date-fns: ^4.1.0
    discord.js: ^14.25.1
    dotenv: ^16.6.1
    esbuild: ^0.27.2
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-plugin-react-hooks: ^5.2.0
    express: ^5.2.1
    flyio: ^0.6.14
    js-yaml: ^4.1.1
    jsonwebtoken: ^9.0.3
    mime-types: ^3.0.2
    node-fetch: ^3.3.2
    only: ^0.0.2
    openai: ^6.15.0
    opusscript: ^0.0.8
    postcss: ^8.5.6
    prettier: 3.7.4
    prism-media: ^1.3.5
    react: ^18.3.1
    react-dom: ^18.3.1
    react-markdown: ^10.1.0
    react-router-dom: ^7.11.0
    reindex: ^0.1.0
    remark-gfm: ^4.0.1
    rimraf: ^6.1.2
    ts-node: ^10.9.2
    ts-node-dev: ^2.0.0
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.0
    winston: ^3.19.0
    ws: ^8.18.3
