packages:
    - packages/*
syncInjectedDepsAfterScripts:
    - build
injectWorkspacePackages: true
catalog:
    '@discordjs/voice': ^0.19.0
    '@eslint/js': ^10.0.1
    '@marsidev/react-turnstile': ^1.4.2
    '@openai/agents': ^0.4.12
    '@sapphire/shapeshift': ^4.0.0
    '@swc/core': ^1.15.11
    '@swc/helpers': ^0.5.18
    '@types/better-sqlite3': ^7.6.13
    '@types/body-parser': ^1.19.6
    '@types/express': ^5.0.6
    '@types/js-yaml': ^4.0.9
    '@types/mime-types': ^3.0.1
    '@types/node': ^25.2.3
    '@types/react': 19.2.14
    '@types/react-dom': 19.2.3
    '@types/ws': ^8.18.1
    '@typescript-eslint/eslint-plugin': ^8.56.0
    '@typescript-eslint/parser': ^8.56.0
    '@vitejs/plugin-react': ^5.1.4
    autoprefixer: ^10.4.24
    better-sqlite3: ^12.6.2
    body-parser: ^2.2.2
    cloudinary: ^2.9.0
    concurrently: ^9.2.1
    copyfiles: ^2.4.1
    cross-env: ^10.1.0
    csstype: 3.2.3
    date-fns: ^4.1.0
    discord.js: ^14.25.1
    dotenv: ^17.3.1
    esbuild: ^0.27.3
    eslint: ^10.0.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-react-hooks: ^7.0.1
    express: ^5.2.1
    flyio: ^0.6.14
    js-yaml: ^4.1.1
    jsonwebtoken: ^9.0.3
    mime-types: ^3.0.2
    node-fetch: ^3.3.2
    only: ^0.0.2
    openai: ^6.22.0
    opusscript: ^0.1.1
    postcss: ^8.5.6
    prettier: 3.8.1
    prism-media: ^1.3.5
    react: ^19.2.4
    react-dom: ^19.2.4
    react-markdown: ^10.1.0
    react-router-dom: ^7.13.0
    reindex: ^0.1.0
    remark-gfm: ^4.0.1
    rimraf: ^6.1.3
    ts-node: ^10.9.2
    ts-node-dev: ^2.0.0
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.1
    winston: ^3.19.0
    ws: ^8.19.0
