app = "daneel-discord-bot"
primary_region = "ord"

[build]
  builder = "heroku/builder:24"

[deploy]
  strategy = "immediate"

[env]
  NODE_ENV = "production"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256