/**
 * @description: Backend-owned weather tool adapter execution + prompt context shaping.
 * Encapsulates fail-open weather tool behavior away from chat orchestrator.
 * @footnote-scope: core
 * @footnote-module: WeatherForecastToolAdapter
 * @footnote-risk: medium - Adapter regressions can degrade weather context quality, but blast radius is one optional tool path.
 * @footnote-ethics: medium - Weather guidance can influence user decisions, so we preserve explicit provenance and failure semantics.
 */
import type { ToolExecutionContext } from '@footnote/contracts/ethics-core';
import type {
    WeatherForecastTool,
    WeatherForecastToolResult,
} from '../weatherGovForecastTool.js';
import type { ChatGenerationWeatherRequest } from '../chatGenerationTypes.js';

const formatWeatherToolResultMessage = (
    result: WeatherForecastToolResult
): string => {
    const compactResult =
        result.status === 'ok'
            ? {
                  toolName: result.toolName,
                  status: result.status,
                  request: result.request,
                  location: result.location,
                  forecast: {
                      generatedAt: result.forecast.generatedAt,
                      updatedAt: result.forecast.updatedAt,
                      periods: result.forecast.periods.map((period) => ({
                          name: period.name,
                          startsAt: period.startsAt,
                          endsAt: period.endsAt,
                          isDaytime: period.isDaytime,
                          temperature: period.temperature,
                          wind: period.wind,
                          shortForecast: period.shortForecast,
                          precipitationProbability:
                              period.precipitationProbability,
                      })),
                  },
                  provenance: result.provenance,
              }
            : result;

    return [
        '// ==========',
        '// BEGIN Backend Tool Result',
        '// weather_forecast result generated by backend adapter',
        '// ==========',
        JSON.stringify(compactResult),
        '// ==========',
        '// END Backend Tool Result',
        '// ==========',
    ].join('\n');
};

export const executeWeatherForecastTool = async ({
    request,
    weatherForecastTool,
    onWarn,
}: {
    request: ChatGenerationWeatherRequest;
    weatherForecastTool: WeatherForecastTool;
    onWarn: (message: string, meta?: Record<string, unknown>) => void;
}): Promise<{
    toolResultMessage?: string;
    toolExecutionContext: ToolExecutionContext;
}> => {
    const weatherToolStartedAt = Date.now();
    try {
        const weatherToolResult =
            await weatherForecastTool.fetchForecast(request);
        const weatherToolDurationMs = Math.max(
            0,
            Date.now() - weatherToolStartedAt
        );
        return {
            toolResultMessage:
                formatWeatherToolResultMessage(weatherToolResult),
            toolExecutionContext: {
                toolName: 'weather_forecast',
                status:
                    weatherToolResult.status === 'ok' ? 'executed' : 'failed',
                ...(weatherToolResult.status === 'error' && {
                    reasonCode: 'tool_execution_error',
                }),
                durationMs: weatherToolDurationMs,
            },
        };
    } catch (error) {
        const weatherToolDurationMs = Math.max(
            0,
            Date.now() - weatherToolStartedAt
        );
        onWarn(
            'weather.gov tool failed open; continuing generation without weather context',
            {
                error: error instanceof Error ? error.message : String(error),
            }
        );
        return {
            toolExecutionContext: {
                toolName: 'weather_forecast',
                status: 'failed',
                reasonCode: 'tool_execution_error',
                durationMs: weatherToolDurationMs,
            },
        };
    }
};
