# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: Deploy app
        permissions:
            contents: read
        runs-on: ubuntu-latest
        concurrency: deploy-${{ matrix.app.name }} # ensure only one deploy per app at a time
        strategy:
            matrix:
                app:
                    - name: backend
                      fly_app: footnote-backend
                      config: deploy/fly.backend.toml
                    - name: web
                      fly_app: footnote-web
                      config: deploy/fly.web.toml
                    - name: bot
                      fly_app: footnote-discord
                      config: deploy/fly.bot.toml
                    - name: bot-myuri
                      fly_app: footnote-discord-myuri
                      config: deploy/fly.bot.toml
                    - name: bot-danny
                      fly_app: footnote-discord-danny
                      config: deploy/fly.bot.toml
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --remote-only --app ${{ matrix.app.fly_app }} -c ${{ matrix.app.config }}
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
